### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-27#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc ergänzen, diese fehlt vollständig
  * Ihre Implementierung geht nicht richtig mit Eingaben zu `encrypt()` um, die ungültige Zeichen enthalten. Diese sollen stillschweigend entfernt werden.

**Comment by thomsmits** [comment]
Die JavaDoc fehlt immer noch. Bitte ergänzen und dann dieses Issue schließen.

**Comment by thomsmits** [comment]
JavaDoc fehlt immer noch.

**Comment by JosueTsafack** [comment]
Hallo Herr Smits,
ich habe schon Java-Doc in meinem Code, ich weiss aber nicht wieso Sie das nicht sehen. vieleicht liegt es an meinem Github. Können Sie mir noch ein bisschen sagen, was Sie konkret mit Java-Doc meinen?  
Danke sehr

**Comment by thomsmits** [comment]
Hallo,

unter
https://github.com/tpe-lecture/repo-27/blob/master/30_testate/01_crypter/src/tpe/testate/crypter/CrypterImpl.java

sieht man die Klasse und darin ist keine JavaDoc. Haben Sie vielleicht vergessen zu pushen?

MfG
Thomas Smits

**Comment by JosueTsafack** [comment]
Ich habe eigentlich eine andere kommentierte Klasse gepusht. Das hier war die erste Version

**Comment by JosueTsafack** [comment]
Hallo Herr Smits,
ich habe herausgefunden warum Sie nicht mein Ergebnis bekommen, Ich kann eigentlich nicht mehr pushen. Ich habe das selbe Problem gehabt wie einer unserer Komilitoren. Ich habe nähmlich was gepusht das nicht zu unserer normalen Aufgaben gehörte, und jetzt wenn ich versuche etwas anderes zu pushen geht es nicht mehr. Und deswegwen wenn ich meine Lösung zum Testat pushe kommt es nicht zu Ihnen.Wie kann ich dieses Problem beheben?
Danke.
